/*
Copyright 2026 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package upcall

import (
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"

	"k8s.io/klog/v2"
)

const (
	containerProxyPath = "/usr/bin/lustre-host-proxy"
	hostUdevDir        = "/host_etc_udev"
	hostProxyPath      = hostUdevDir + "/lustre-host-proxy"
	hostRulesPath      = hostUdevDir + "/rules.d/99-lustre.rules"

	udevRuleContent = `# Generated by Lustre CSI Driver Node Init. Do not edit.
SUBSYSTEM=="lustre", ACTION=="change", ENV{PARAM}=="?*", RUN+="/etc/udev/lustre-host-proxy /usr/sbin/lctl set_param $env{PARAM}=$env{SETTING}"
`
)

// SetupHostArtifacts deploys the static Go proxy binary and the udev rules to the host filesystem via the /host_etc_udev mount.
func SetupHostArtifacts() error {
	klog.Infof("Initializing Lustre upcall host artifacts via %s", hostUdevDir)

	// 1. Verify host mount exists.
	if _, err := os.Stat(hostUdevDir); err != nil {
		return fmt.Errorf("host udev mount directory %s missing or inaccessible: %w", hostUdevDir, err)
	}

	// 2. Copy the proxy binary from container to host.
	if err := copyFile(containerProxyPath, hostProxyPath); err != nil {
		return fmt.Errorf("failed to copy proxy binary to host: %w", err)
	}

	// 3. Make the host proxy executable.
	if err := os.Chmod(hostProxyPath, 0755); err != nil {
		return fmt.Errorf("failed to set executable permissions on host proxy: %w", err)
	}
	klog.Infof("Successfully installed host proxy binary at %s", hostProxyPath)

	// 4. Create symbolic link on host pointing to the proxy: /etc/udev/l_gssiam_upcall -> /etc/udev/lustre-host-proxy
	hostSymlinkPath := filepath.Join(hostUdevDir, "l_gssiam_upcall")
	if err := os.Remove(hostSymlinkPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to remove existing symlink at %s: %w", hostSymlinkPath, err)
	}
	if err := os.Symlink(hostProxyPath, hostSymlinkPath); err != nil {
		return fmt.Errorf("failed to create upcall symlink at %s: %w", hostSymlinkPath, err)
	}
	klog.Infof("Successfully created host upcall symlink at %s -> %s", hostSymlinkPath, hostProxyPath)

	// 5. Configure kernel tunable sptlrpc.gssiam.gssiam_upcall directly to the symlink.
	cmd := exec.Command("/usr/sbin/lctl", "set_param", "sptlrpc.gssiam.gssiam_upcall=/etc/udev/l_gssiam_upcall")
	if output, err := cmd.CombinedOutput(); err != nil {
		klog.Warningf("Failed to set kernel tunable sptlrpc.gssiam.gssiam_upcall (module may not be loaded yet): %v, output: %s", err, string(output))
	} else {
		klog.Infof("Successfully set kernel tunable sptlrpc.gssiam.gssiam_upcall=/etc/udev/l_gssiam_upcall, output: %s", string(output))
	}

	// 6. Ensure rules.d directory exists on host.
	rulesDir := filepath.Dir(hostRulesPath)
	if err := os.MkdirAll(rulesDir, 0755); err != nil {
		return fmt.Errorf("failed to create host rules directory %s: %w", rulesDir, err)
	}

	// 5. Write the udev rules file
	if err := os.WriteFile(hostRulesPath, []byte(udevRuleContent), 0644); err != nil {
		return fmt.Errorf("failed to write udev rules to host at %s: %w", hostRulesPath, err)
	}
	klog.Infof("Successfully installed udev rules at %s", hostRulesPath)

	return nil
}

func copyFile(src, dst string) error {
	sourceFile, err := os.Open(src)
	if err != nil {
		return err
	}
	defer func() { _ = sourceFile.Close() }()

	destFile, err := os.OpenFile(dst, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0755)
	if err != nil {
		return err
	}
	defer func() { _ = destFile.Close() }()

	if _, err = io.Copy(destFile, sourceFile); err != nil {
		return err
	}
	return destFile.Sync()
}
